# Generated by Django 5.0.1 on 2024-01-20 18:05

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to="profiles"),
            preserve_default=False,
        ),
    ]
